name: ecommerce_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"
  flutter: ">=3.10.2"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  carousel_slider: ^4.2.1
  animate_do: ^3.1.2
  advance_notification: ^1.0.6
  badges: ^3.1.2
  line_icons: ^2.0.3
  bottom_bar_matu: ^1.3.0
  razorpay_flutter: ^1.3.5
  fluttertoast: ^8.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: AlegreyaSans
      fonts:
        - asset: assets/fonts/AlegreyaSans-Bold.ttf
        - asset: assets/fonts/AlegreyaSans-Medium.ttf




